<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'user_catalogue_id' => 1,
                'name' => 'Nguyễn Văn An',
                'email' => 'nguyen.van.an@example.com',
                'phone' => '0901111222',
                'district_id' => null,
                'address' => 'Số 10, Phố Huế, Hai Bà Trưng, Hà Nội',
                'birthday' => '1985-03-15',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => true,
                'description' => 'Quản trị viên hệ thống cao cấp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 2,
                'name' => 'Trần Thị Bình',
                'email' => 'tran.thi.binh@example.com',
                'phone' => '0902222333',
                'district_id' => null,
                'address' => 'Số 25, Láng Hạ, Đống Đa, Hà Nội',
                'birthday' => '1978-07-20',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => true,
                'description' => 'Giám đốc điều hành',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 3,
                'name' => 'Lê Văn Cường',
                'email' => 'le.van.cuong@example.com',
                'phone' => '0903333444',
                'district_id' => null,
                'address' => 'Số 45, Trần Duy Hưng, Cầu Giấy, Hà Nội',
                'birthday' => '1990-11-05',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Trưởng phòng Nhân sự',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 4,
                'name' => 'Phạm Thị Dung',
                'email' => 'pham.thi.dung@example.com',
                'phone' => '0904444555',
                'district_id' => null,
                'address' => 'Số 88, Giảng Võ, Ba Đình, Hà Nội',
                'birthday' => '1987-04-12',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Kế toán trưởng',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 5,
                'name' => 'Hoàng Văn Em',
                'email' => 'hoang.van.em@example.com',
                'phone' => '0905555666',
                'district_id' => null,
                'address' => 'Số 123, Nguyễn Trãi, Thanh Xuân, Hà Nội',
                'birthday' => '1992-09-28',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Trưởng phòng Kinh doanh',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 6,
                'name' => 'Vũ Thị Hoa',
                'email' => 'vu.thi.hoa@example.com',
                'phone' => '0906666777',
                'district_id' => null,
                'address' => 'Số 56, Thái Hà, Đống Đa, Hà Nội',
                'birthday' => '1994-01-18',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên Marketing',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 7,
                'name' => 'Đặng Văn Giang',
                'email' => 'dang.van.giang@example.com',
                'phone' => '0907777888',
                'district_id' => null,
                'address' => 'Số 99, Tôn Đức Thắng, Đống Đa, Hà Nội',
                'birthday' => '1988-06-22',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Trưởng phòng IT',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 8,
                'name' => 'Bùi Thị Hương',
                'email' => 'bui.thi.huong@example.com',
                'phone' => '0955667788',
                'district_id' => null,
                'address' => 'Số 234, Xã Đàn, Đống Đa, Hà Nội',
                'birthday' => '1995-12-10',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Product Manager',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 9,
                'name' => 'Đinh Văn Khải',
                'email' => 'dinh.van.khai@example.com',
                'phone' => '0966778899',
                'district_id' => null,
                'address' => 'Số 78, Lê Duẩn, Hoàn Kiếm, Hà Nội',
                'birthday' => '1993-05-07',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên chăm sóc khách hàng',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 10,
                'name' => 'Mai Thị Lan',
                'email' => 'mai.thi.lan@example.com',
                'phone' => '0977889900',
                'district_id' => null,
                'address' => 'Số 145, Kim Mã, Ba Đình, Hà Nội',
                'birthday' => '1991-08-30',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Quản lý Logistics',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 11,
                'name' => 'Ngô Văn Minh',
                'email' => 'ngo.van.minh@example.com',
                'phone' => '0988990011',
                'district_id' => null,
                'address' => 'Số 67, Nguyễn Chí Thanh, Đống Đa, Hà Nội',
                'birthday' => '1986-02-14',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Luật sư tư vấn',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 12,
                'name' => 'Phan Thị Nga',
                'email' => 'phan.thi.nga@example.com',
                'phone' => '0999001122',
                'district_id' => null,
                'address' => 'Số 189, Cầu Giấy, Cầu Giấy, Hà Nội',
                'birthday' => '1996-10-25',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên truyền thông nội bộ',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 13,
                'name' => 'Lý Văn Phong',
                'email' => 'ly.van.phong@example.com',
                'phone' => '0913000001',
                'district_id' => null,
                'address' => 'Số 321, Đê La Thành, Đống Đa, Hà Nội',
                'birthday' => '1989-07-16',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên nghiên cứu thị trường',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 14,
                'name' => 'Dương Thị Quỳnh',
                'email' => 'duong.thi.quynh@example.com',
                'phone' => '0913000002',
                'district_id' => null,
                'address' => 'Số 456, Khương Thượng, Đống Đa, Hà Nội',
                'birthday' => '1992-03-08',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'QA Engineer',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 15,
                'name' => 'Trịnh Văn Sơn',
                'email' => 'trinh.van.son@example.com',
                'phone' => '0913000003',
                'district_id' => null,
                'address' => 'Số 234, Ô Chợ Dừa, Đống Đa, Hà Nội',
                'birthday' => '1987-11-19',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Kiểm soát viên nội bộ',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 16,
                'name' => 'Võ Thị Thảo',
                'email' => 'vo.thi.thao@example.com',
                'phone' => '0913000004',
                'district_id' => null,
                'address' => 'Số 567, Trường Chinh, Thanh Xuân, Hà Nội',
                'birthday' => '1994-09-02',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên mua hàng',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 17,
                'name' => 'Hồ Văn Tùng',
                'email' => 'ho.van.tung@example.com',
                'phone' => '0913000005',
                'district_id' => null,
                'address' => 'Số 789, Nguyễn Lương Bằng, Đống Đa, Hà Nội',
                'birthday' => '1990-04-27',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Project Manager',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 18,
                'name' => 'Đỗ Thị Uyên',
                'email' => 'do.thi.uyen@example.com',
                'phone' => '0913000006',
                'district_id' => null,
                'address' => 'Số 890, Lê Văn Lương, Thanh Xuân, Hà Nội',
                'birthday' => '1993-06-11',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên pháp chế',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 19,
                'name' => 'Cao Văn Vinh',
                'email' => 'cao.van.vinh@example.com',
                'phone' => '0913000007',
                'district_id' => null,
                'address' => 'Số 345, Phạm Hùng, Nam Từ Liêm, Hà Nội',
                'birthday' => '1991-12-05',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Data Analyst',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 20,
                'name' => 'Tô Thị Xuân',
                'email' => 'to.thi.xuan@example.com',
                'phone' => '0913000008',
                'district_id' => null,
                'address' => 'Số 678, Mễ Trì, Nam Từ Liêm, Hà Nội',
                'birthday' => '1988-01-29',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Security Engineer',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 21,
                'name' => 'Lâm Văn Yên',
                'email' => 'lam.van.yen@example.com',
                'phone' => '0913000009',
                'district_id' => null,
                'address' => 'Số 901, Lạc Long Quân, Tây Hồ, Hà Nội',
                'birthday' => '1995-08-14',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên đào tạo',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 22,
                'name' => 'Chu Thị Ánh',
                'email' => 'chu.thi.anh@example.com',
                'phone' => '0913000010',
                'district_id' => null,
                'address' => 'Số 112, Võ Chí Công, Tây Hồ, Hà Nội',
                'birthday' => '1992-02-21',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Partnership Manager',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 23,
                'name' => 'Hà Văn Bình',
                'email' => 'ha.van.binh@example.com',
                'phone' => '0913000011',
                'district_id' => null,
                'address' => 'Số 223, Xuân Thủy, Cầu Giấy, Hà Nội',
                'birthday' => '1989-05-18',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Operations Manager',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 24,
                'name' => 'Kiều Thị Châu',
                'email' => 'kieu.thi.chau@example.com',
                'phone' => '0913000012',
                'district_id' => null,
                'address' => 'Số 334, Dương Đình Nghệ, Cầu Giấy, Hà Nội',
                'birthday' => '1994-07-09',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'Chuyên viên quản lý tài sản',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_catalogue_id' => 25,
                'name' => 'Ông Văn Đạt',
                'email' => 'ong.van.dat@example.com',
                'phone' => '0913000013',
                'district_id' => null,
                'address' => 'Số 445, Nguyễn Khang, Cầu Giấy, Hà Nội',
                'birthday' => '1996-11-23',
                'avatar' => null,
                'publish' => 1,
                'is_admin' => false,
                'description' => 'CX Specialist',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}